CREATE TABLE ALK_FIELD_DEFINITION
(
    M_ID                      NUMBER(10) NOT NULL,
    F_ID                      NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    F_DOMAIN_NO               NUMBER(10) NOT NULL,
    F_NAME                    VARCHAR2(50) NOT NULL,
    F_ALIAS_NAME              VARCHAR2(10) DEFAULT NULL,
    F_FIXED                   NUMBER(1) NOT NULL,
    F_LENGTH                  NUMBER(10) NOT NULL,
    F_MAX_LENGTH              NUMBER(10) NOT NULL,
    F_CLASS_NAME              VARCHAR2(100) DEFAULT NULL,
    F_PATTERN                 VARCHAR2(20) DEFAULT NULL,
    F_REMARK                  VARCHAR2(100) NOT NULL,
    F_STATUS                  VARCHAR2(10) NOT NULL,
    F_PAGE_SIZE_NAME          VARCHAR2(50) DEFAULT NULL,
    F_PARSE_TYPE              VARCHAR2(10) NOT NULL,
    F_LEN_PARSE_TYPE          VARCHAR2(10) DEFAULT NULL,
    F_EXIST_SUBDOMAIN         NUMBER(1) NOT NULL,
    F_SUBDOMAIN_TYPE          VARCHAR2(10) DEFAULT NULL,
    F_NON_SUBDOMAIN_EXCEPTION NUMBER(1) DEFAULT NULL
);

COMMENT ON TABLE ALK_FIELD_DEFINITION IS '报文域定义表';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.M_ID IS 'ALK_MESSAGE_DEFINITION主键';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_ID IS '主键';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_DOMAIN_NO IS '域序号';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_NAME IS '域名称';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_ALIAS_NAME IS '域别名';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_FIXED IS '是否定长';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_LENGTH IS '域字节长度';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_MAX_LENGTH IS '域最大长度';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_CLASS_NAME IS '域java类型';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_PATTERN IS '域值格式，日期类型使用';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_REMARK IS '域描述';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_STATUS IS '状态';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_PAGE_SIZE_NAME IS '分页记录数字段名称';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_PARSE_TYPE IS '域解析类型';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_LEN_PARSE_TYPE IS '变长域解析类型';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_EXIST_SUBDOMAIN IS '是否存在子域';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_SUBDOMAIN_TYPE IS '子域类型';
COMMENT ON COLUMN ALK_FIELD_DEFINITION.F_NON_SUBDOMAIN_EXCEPTION IS '未配置子域异常';

CREATE TABLE ALK_MESSAGE_DEFINITION
(
    M_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    F_ID          NUMBER(10) DEFAULT NULL,
    M_TYPE        VARCHAR2(10) NOT NULL,
    M_GROUP       VARCHAR2(20) NOT NULL,
    M_CODE        VARCHAR2(20) NOT NULL,
    M_KIND        VARCHAR2(20) NOT NULL,
    M_DOMAIN      VARCHAR2(20) DEFAULT NULL,
    M_USAGE       VARCHAR2(2) DEFAULT NULL,
    M_DOMAIN_TYPE VARCHAR2(10) DEFAULT NULL,
    M_HOLDER      VARCHAR2(100) DEFAULT NULL,
    M_CHARSET     VARCHAR2(100) DEFAULT NULL,
    M_REMARK      VARCHAR2(100) NOT NULL,
    M_ENABLED     NUMBER(1) NOT NULL,
    CONSTRAINT UK_ALK_MESSAGE_DEFINITION UNIQUE (M_TYPE, M_GROUP, M_CODE, M_KIND, M_DOMAIN, M_USAGE)
);

COMMENT ON TABLE ALK_MESSAGE_DEFINITION IS '报文定义表';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_ID IS '主键';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.F_ID IS 'ALK_FIELD_DEFINITION主键';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_TYPE IS '报文类型 iso: 8583 fixed: 固定格式';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_GROUP IS '报文分组';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_CODE IS '报文交易码';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_KIND IS '报文种类';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_DOMAIN IS '报文子域名称';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_USAGE IS '8583报文子域usage';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_DOMAIN_TYPE IS '报文域类型';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_HOLDER IS '报文实体类';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_CHARSET IS '报文编码';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_REMARK IS '报文描述';
COMMENT ON COLUMN ALK_MESSAGE_DEFINITION.M_ENABLED IS '是否可用';